/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CharacterPage: typeof import('./components/CharacterPage.vue')['default']
    Characters: typeof import('./components/Characters.vue')['default']
    Episodes: typeof import('./components/Episodes.vue')['default']
    LoadingImgage: typeof import('./components/LoadingImgage.vue')['default']
    Locations: typeof import('./components/Locations.vue')['default']
    NavbarDesktop: typeof import('./components/NavbarDesktop.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
